### ISSUE TITLE
Package version not updated on Anaconda website

### ISSUE THREAD

**Issue by mrfitzpa** [conda-forge/fancytypes-feedstock#2]
### Comment:

I recently updated the recipe such that the most recent version is 1.0.0 and have appeared to successfully merged this change to the main branch. However, it's been almost a day and the version hasn't updated on the corresponding Anaconda [page](https://anaconda.org/conda-forge/fancytypes), it still shows as 0.0.1. 

On a possibly related note, I had to update the recipe manually as the bot did not do so automatically. 

@conda-forge/core please advise, many thanks in advance.

**Comment by h-vetinari** [comment]
It happens something like once every ~100 times or less that builds don't get triggered upon merging. In such cases, what you can do is (let's assume your own remote is `origin` and the feedstock's one is `upstream`)
```
git checkout main
git reset --hard upstream/main  # or otherwise ensure that you're on the exact same commit as the feedstock
git commit --allow-empty -m "retrigger CI"
git push upstream main
```
This will push an empty commit to the main branch of the feedstock (something we ask maintainers _not_ to do generally, but this is an exception) and this will then successfully trigger a build. In this case, I've done it for you manually in azure pipelines itself (i.e. without the empty commit; only core members can do that though).

PS. please fix the SPDX license identifier, as the linter asks you to. ;-)

**Comment by mrfitzpa** [comment]
> It happens something like once every ~100 times or less that builds don't get triggered upon merging. In such cases, what you can do is (let's assume your own remote is `origin` and the feedstock's one is `upstream`)
> 
> ```
> git checkout main
> git reset --hard upstream/main  # or otherwise ensure that you're on the exact same commit as the feedstock
> git commit --allow-empty -m "retrigger CI"
> git push upstream main
> ```
> 
> This will push an empty commit to the main branch of the feedstock (something we ask maintainers _not_ to do generally, but this is an exception) and this will then successfully trigger a build. In this case, I've done it for you manually in azure pipelines itself (i.e. without the empty commit; only core members can do that though).
> 
> PS. please fix the SPDX license identifier, as the linter asks you to. ;-)

Thanks for your help! And terribly sorry about the SPDX license identifier bug --- still getting used to things around here! I'll be sure to fix it.
